spring:
  datasource:
    username: root
    url: jdbc:mysql://121.199.72.11:3306/interview
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    settings:
      template_update_delay: 0
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    template-loader-path: classpath:/templates
fastparse:
  base-package: a.a

